[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "coordinator"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
verifier_router = { git = "https://github.com/boundless-xyz/risc0-solana", tag = "v3.0.0", package = "verifier_router", features = [
    "cpi",
] }
groth_16_verifier = { git = "https://github.com/boundless-xyz/risc0-solana", tag = "v3.0.0", package = "groth_16_verifier" }
consumer = { path = "../consumer", features = ["cpi"] }

[dev-dependencies]
litesvm = "0.10"
solana-keypair = "3"
solana-signer = "3"
solana-transaction = "3"
solana-account = "3"
solana-instruction = "3"
solana-sdk-ids = "3"
borsh = "0.10.3"
verifier_router = { git = "https://github.com/boundless-xyz/risc0-solana", tag = "v3.0.0", package = "verifier_router", features = [
    "cpi",
] }
groth_16_verifier = { git = "https://github.com/boundless-xyz/risc0-solana", tag = "v3.0.0", package = "groth_16_verifier" }
