[workspace]
members = [
    "core",
    ".",
    "methods",
    "integration_tests",
]
exclude = [
    "methods/guest",
]
resolver = "2"

[workspace.dependencies]
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3", features = ["host"] }
nssa = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3", features = ["test-utils"] }
spel-framework = { git = "https://github.com/logos-co/spel.git", tag = "v0.3.0", package = "spel-framework" }
spel-framework-macros = { git = "https://github.com/logos-co/spel.git", tag = "v0.3.0", package = "spel-framework-macros" }
tuniq-shared-types = { path = "../shared-types" }
predicate_core = { path = "core" }
predicate_program = { path = "." }
risc0-zkvm = { version = "=3.0.5" }
risc0-build = { version = "=3.0.5" }
borsh = { version = "1.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
unsafe_code = "deny"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious  = { level = "deny", priority = -1 }
perf        = { level = "deny", priority = -1 }

[package]
name = "predicate_program"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
nssa_core = { workspace = true }
predicate_core = { workspace = true }
